accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('stylist_signup/', views.StylistSignUp.as_view(), name = 'stylist_signup'),
    path('stylist_signup_success', views.stylist_signup_success, name = 'stylist_success'),
    path('client_signup/', views.ClientSignUp.as_view(), name = 'client_signup'),
    path('user_delete//<int:pk>/', views.UserDeleteView.as_view(), name = 'user_delete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),


]

# 1. Submit email form                         -> PasswordResetView.as_view()
# 2. Email sent success message               -> PasswordResetDoneView.as_view(password_reset_done)
# 3. Link to password reset form in mail      -> PasswordResetConfirmView.as_view()
# 4. Password successfully changed message      -> PasswordResetCompleteView.as_view()

client_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'client_app'

urlpatterns = [
    path('client_subscribe/', views.subscription, name='subscribe'),
    path('client_detail/<int:pk>/', views.viewClient, name='client_detail'),
    path('add_favourite/<int:pk>/', views.addFavourite, name='add_favourite'),
    path('remove_favourite/<int:pk>/', views.removeFavourite, name='remove_favourite'),
    path('add_review/<int:pk>/', views.addReview, name='add_review'),
    path('view_review/<int:pk>/', views.viewReview, name='view_review'),
    path('update_review/<int:pk>/', views.updateReview, name='update_review'),
    path('delete_review/<int:pk>/', views.deleteReview, name='delete_review'),
    
]

stylist_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'stylist_app'

urlpatterns = [
    path('stylist_home/', views.StylistHome.as_view(), name = 'stylist_home'),
    path('stylist_detail/<int:pk>/', views.viewStylist, name = 'stylist_detail'),
    path('stylists', views.listStylists, name = 'stylists_view'),
    path('stylist_update/<int:pk>/', views.updateStylist, name = 'stylist_update'),
    path('stylist_contact/<int:pk>/', views.updateStylistContact, name = 'stylist_contact_update'),
    path('service_create/<int:pk>/', views.createService, name = 'service_create'),
    path('service_update/<int:pk>/', views.updateService, name = 'service_update'),
    path('service_delete/<int:pk>/', views.deleteService, name = 'service_delete'),
    path('salon_create/<int:pk>/', views.createSalon, name = 'salon_create'),
    path('portfolio_item_create/<int:pk>/', views.createPortfolio, name = 'portfolio_item_create'),
    path('portfolio_view/<int:pk>/', views.viewPortfolio, name = 'portfolio_view'),
    path('portfolio_update/<int:pk>/', views.updatePortfolio, name = 'portfolio_update'),
    path('portfolio_delete/<int:pk>/', views.deletePortfolio, name = 'portfolio_delete'),
    path('search_stylist/', views.searchStylist, name='search'),
    path('searched_stylist/<region_pk>/<hairstyle_pk>/', views.searchedStylists, name='searched_stylists')

]

stylist_app/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class HairstyleCategory(models.Model):
    name = models.CharField(max_length=128, blank=True)
    image = models.ImageField(upload_to='hairstyle_catergories/', blank=True)

    def __str__(self):
        return self.name

    def get_hairstyles(self):
        return Hairstyle.objects.filter(hairstyle_catergories=self.name)

class ProductCategory(models.Model):
    name = models.CharField(max_length=128, blank=True)
    image = models.ImageField(upload_to='product_catergories/', blank=True)

    def __str__(self):
        return self.name

class Hairstyle(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey(HairstyleCategory, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField(max_length=60, blank=True)
    hairstyle_image = models.ImageField(upload_to='hairstyle_eg/', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', 'category__name')


class Product(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField(max_length=254, blank=True)
    product_image = models.ImageField(upload_to='product_eg/', blank=True)

    def __str__(self):
        return self.name




# Create your models here.

stylist_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import (TemplateView)
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from accounts import models
from stylist_app.models import Hairstyle, Product, HairstyleCategory
from .forms import StylistForm, ServiceForm, SalonForm, PortfolioForm, StylistContactForm
from accounts.forms import UserForm


class StylistHome(TemplateView):
     template_name = 'stylist_home.html'

## -------------------------------Stylist Functions________________________________________________

def is_valid_queryparam(param):
    return param != '' and param is not None

def listStylists(request):
    # stylists = models.Stylist.objects.all().order_by('-user__date_joined')
    stylists = models.Stylist.objects.all().order_by('user__name')
    hairstyles = models.Hairstyle.objects.filter(stylist__in =stylists).distinct().order_by('category')
    services = models.ServiceOffering.objects.filter(stylist__in=stylists)
    regions = models.Region.objects.filter(stylist__in=stylists).distinct().order_by('city')

    # city = models.City.objects.filter(region__in=regions).distinct()


    name_query = request.GET.get('stylist_name')
    region_query = request.GET.get('region_name')
    hairstyle_query = request.GET.get('hairstyle_name')
    house_call_query = request.GET.get('house_call')
    # signiture_query = request.GET.get('signiture_hairstyle_name')
    # rating_query = request.GET.get('rating_name')
    # city_query = request.GET.get('city_name')



    if is_valid_queryparam(name_query):
        stylists = stylists.filter(user__name__icontains=name_query)

    if is_valid_queryparam(region_query):
        stylists = stylists.filter(Q(region__name = region_query))

    if is_valid_queryparam(hairstyle_query):
         stylists = stylists.filter(hairstyles__name = hairstyle_query)

    if house_call_query == 'on':
        stylists = stylists.filter(house_calls=True)

    p = Paginator(stylists, 6)

    page_num = request.GET.get('page', 1)

    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)

    context = {'stylists':page, 'hairstyles':hairstyles, 'services':services, 'regions':regions}
    return render(request, 'stylist_app/view_stylists.html', context)

def searchedStylists(request, region_pk, hairstyle_pk):

    if region_pk != 'None':
        stylists = models.Stylist.objects.filter(region__pk = int(region_pk))
    else:
        hairstyle = models.Hairstyle.objects.get(pk = int(hairstyle_pk))
        stylists = hairstyle.stylist_set.all()


    services = models.ServiceOffering.objects.filter(stylist__in=stylists)

    context = {'stylists':stylists, 'services':services}
    return render(request, 'stylist_app/searched_stylists.html', context)

@login_required
def viewStylist(request, pk):
    user = request.user
    stylist = models.Stylist.objects.get(pk=pk)
    reviews = models.Review.objects.filter(stylist=stylist)
    services = stylist.stylist_hairstyles.all()
    portfolio = stylist.portfolio_set.all()

    category = []

    for service in services:
        category.append(service.category)
    categories = set(category)

    profile_items = {'profile_pic': 0, 'bio':0,
                    'region':0, 'hairstyle':0,
                    'portfolio':0, 'phone':0}
    completeness = 0
    if stylist.profile_pic != "profile_pics/default_stylist.png":
        profile_items['profile_pic'] = 1
    if stylist.bio:
        profile_items['bio'] = 1
    if stylist.region:
        profile_items['region'] = 1
    if stylist.stylist_hairstyles.first():
        profile_items['hairstyle'] = 1
    if stylist.portfolio_set.first():
        profile_items['portfolio'] = 1
    if stylist.phone_number:
        profile_items['phone'] = 1

    for k, v in profile_items.items():
        completeness += v
        profile_completeness = (completeness/6)*100

    context = {'user': user, 'services': services, 'stylist': stylist,
                'portfolio': portfolio, 'categories': categories,
                'profile_completeness':profile_completeness,
                'profile_items':profile_items, 'reviews': reviews}
    return render(request, 'stylist_app/stylist_detail.html', context)



def updateStylist(request, pk):
    stylist = models.Stylist.objects.get(pk=pk)
    form = StylistForm(instance=stylist)
    user_form = UserForm(instance=stylist.user)
    contact_form = StylistContactForm(instance=stylist)

    if request.method == 'POST':
        form = StylistForm(request.POST, request.FILES, instance=stylist)
        user_form = UserForm(request.POST, instance=stylist.user)
        contact_form = StylistContactForm(request.POST, instance=stylist)

        if form.is_valid() and user_form.is_valid() and contact_form.is_valid():
            form.save()
            user_form.save()
            contact_form.save()
            messages.success(request, 'Your profile has been updated')
            return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
        else:
            return HttpResponse("Oops looks like something went wrong. Please try again")

    context = {'form':form, 'user_form': user_form, 'contact_form': contact_form}
    return render(request, 'stylist_app/stylist_form.html', context)

def updateStylistContact(request, pk):
    stylist = models.Stylist.objects.get(pk=pk)
    contact_form = StylistContactForm(instance=stylist)

    if request.method == 'POST':
        contact_form = StylistContactForm(request.POST, instance=stylist)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, 'Your contact details have been updated')
            return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))

    context = {'contact_form':contact_form}
    return render(request, 'stylist_app/stylist_contact_form.html', context)



##---------------------------------------------Services ---------------------------------------------------------------------------

def limit_top_styles(styles, limit):
    if styles.filter(top_style=True).all().count() < limit:
        return True
    else:
        return False




def createService(request, pk):
    stylist = models.Stylist.objects.get(pk=pk)
    hairstyles = models.Hairstyle.objects.all()
    categories = models.HairstyleCategory.objects.all()
    current_services = stylist.stylist_hairstyles.all()
    form = ServiceForm

    if current_services.count() > 9:
        messages.error(request, "Sorry, you can't have more than 10 hairstyles")
        return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))

    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.stylist = stylist
            if instance.top_style == True:
                if limit_top_styles(current_services, 3):
                    try:
                        instance.save()
                        messages.success(request, 'Hairstyle has been added')
                        return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
                    except IntegrityError:
                        return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
                        messages.error(request, 'Sorry, you already have this hairstyle')
                else:
                    messages.error(request, "Sorry, you can't have more than 3 signiture hairstyles")
                    return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
            else:
                try:
                    instance.save()
                    messages.success(request, 'Hairstyle has been added')
                    return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
                except IntegrityError:
                    return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
                    messages.error(request, 'Sorry, you already have this hairstyle')

    context = {'stylist':stylist, 'form': form}
    return render(request, 'stylist_app/hair_form.html', context)

def updateService(request, pk):
    service = models.ServiceOffering.objects.get(pk=pk)
    stylist = service.stylist
    current_services = stylist.stylist_hairstyles.all()

    form = ServiceForm(instance=service)
    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            if limit_top_styles(current_services, 3):
                try:
                    form.save()
                    messages.success(request, 'Hairstyle has been updated')
                    return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
                except IntegrityError:
                    messages.error(request, 'Sorry, you already have this hairstyle')
                    return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
            else:
                messages.error(request, "Sorry, you can't have more than 3 signiture hairstyles")
                return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))

    context = {'form':form}
    return render(request, 'stylist_app/hair_form.html', context)


def deleteService(request, pk):
    service = models.ServiceOffering.objects.get(pk=pk)
    stylist = service.stylist

stylist_app/templates/stylist_app/_stylist_contacts.html
{% load static %}
<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
        <div class="row">

          <div class="col-sm-6">
            <p><strong>Location:</strong> {{ stylist.region }} ({{ stylist.region.city }})</p>
            <p><strong>Phone: </strong> {{ stylist.phone_number }}</p>
            <p><strong>House Calls: </strong>
              {% if stylist.house_calls %} Yes
              {% else %} No
              {% endif %}</p>

              {% if stylist.facebook %}
                <a href="{{ stylist.facebook}}"><img src="{% static "images/facebook_icon1.jpg" %}" alt="facebook"></a>
              {% endif %}

              {% if stylist.instagram %}
                <a href="{{ stylist.instagram}}"><img src="{% static "images/insta_icon1.jpg" %}" alt="instagram"></a>
              {% endif %}
          </div>

          <div class="col-sm-6">

            {% if stylist.salon %}
              <p><strong>Salon: </strong>{{ stylist.salon.name }}</p>
              <p><strong>Salon Address: </strong>{{stylist.salon.address}}, {{stylist.salon.region}}, {{stylist.salon.region.city}}</p>
              <p><strong>Salon Contact: </strong>{{stylist.salon.phone_number}}</p>
            {% endif %}

            {% if user.pk == stylist.user.pk %}
              <p>(<a href="{% url 'stylist_app:salon_create' pk=stylist.pk %}"">Salon not on list? Click here to add Salon Details</a>)</p>
            {% endif %}

          </div>

        </div>

        {% if user.pk == stylist.user.pk %}
          <div class="row m-3">
            <a class = 'btn btn-outline-dark btn-block' href="{% url 'stylist_app:stylist_contact_update' pk=stylist.pk%}">Update Contact Details</a>
          </div>
        {% endif %}

  </div>

stylist_app/templates/stylist_app/_stylist_hairstyles.html
{% load static %}
<div class="tab-pane fade show active" id="nav-styles" role="tabpanel" aria-labelledby="nav-styles-tab">
  {% if not services %}
    {% if user.pk == stylist.user.pk %}
    <div class="alert alert-dark alert-dismissible fade show text-center" role="alert">
      <span>Add hairstyles to show your customers what you offer</span>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

     <div class="row m-3">
       <a class = 'btn btn-outline-dark btn-block' href="{% url 'stylist_app:service_create' pk=stylist.pk%}">Add Hairstyle</a>
     </div>

    {% endif %}
  {% else %}

  <div class="stylist-menu-body">
    {% if user.pk == stylist.user.pk %}
      <div class="row m-3">
        <a class = 'btn btn-outline-dark btn-block' href="{% url 'stylist_app:service_create' pk=stylist.pk%}">Add Hairstyle</a>
      </div>
    {% endif %}

    {% for category in categories %}

    <!-- Section starts: Appetizers -->
    <div class="mb-4">
      <h3 class="menu-section-title">{{category.name}}</h3>
        {% for service in services %}
          {% if service.category == category %}
          <div class="menu-item">
            <div class="menu-item-name">
              {{service.hairstyle.name}}

              {% if service.top_style %}
                <i class="fas fa-star" style="color:gold"></i>
              {% endif %}
            </div>

            <div class="menu-item-price">

              {% if service.price %}
                <p>R{{service.price}}</p>
              {% else %}
                <p>POA</p>
              {% endif %}

            </div>

            <div class="menu-item-description">
              {{service.description}}
            </div>

            {% if user.pk == stylist.user.pk %}
            <a href="{% url 'stylist_app:service_update' pk=service.pk %}">(Edit)</a>
            <a href="{% url 'stylist_app:service_delete' pk=service.pk %}">(Delete)</a>
            {% endif %}

          </div><!-- <div class="menu-item"> -->

          {% endif %}
        {% endfor %}
      </div><!-- <div class="menu-section"> -->

    {% endfor %}

    {% if user.pk == stylist.user.pk %}
      <div class="row m-3">
        <a class = 'btn btn-outline-dark btn-block' href="{% url 'stylist_app:service_create' pk=stylist.pk%}">Add Hairstyle</a>
      </div>
    {% endif %}
  </div><!-- <div class="menu-body"> -->

  {% endif %}

</div>

stylist_app/templates/stylist_app/_stylist_reviews.html
{% load static %}
<div class="tab-pane fade" id="nav-reviews" role="tabpanel" aria-labelledby="nav-reviews-tab">

  {% if reviews %}
    {% for review in reviews %}

      <div class="row">
        <div class="col-sm-3">
          <ul style="list-style-type:none;">
            <li style="font-size:150%"><span class="badge bg-secondary">{{review.total_rating}}</span></li>
            <li>By: {{review.client.user.name}}</li>
            <li style="font-size:75%"><em>{{review.created|date:"D, d-m-Y"}}</em></li>
          </ul>
        </div>

        <div class="col-sm-9">
          <ul style="list-style-type:none;">
            <li>Appointment: {{review.appointment|date:"D, d-m-Y"}}</li>
            <li><strong>Money:</strong> {{review.value}}/5, <strong>Hygiene:</strong> {{review.hygiene}}/5, <strong>Expectations:</strong> {{review.expectation}}/5,
                <strong>Skill:</strong> {{review.craft}}/5, <strong>Professionalism:</strong> {{review.professional}}/5</li>
            <li><em>'{{review.comment}}'</em></li>
            <li>Recommended: {{review.recommendation}}</li>
          </ul>
        </div>
      </div>

      {% if user.pk == review.client.user.pk %}
        <a class='btn btn-outline-dark' href="{% url 'client_app:update_review' pk=review.pk%}">Update</a>
        <a class='btn btn-outline-danger' href="{% url 'client_app:delete_review' pk=review.pk%}">Delete</a>
      {% endif %}

      {% if user.pk == review.stylist.user.pk %}
        <a class='btn btn-outline-danger' href="#">Report this Review</a>
      {% endif %}

      <hr>
    {% endfor%}
  {% else %}
    <p class='lead text-center'>You currently don't have any reviews.</p>
  {% endif %}



</div>

stylist_app/templates/stylist_app/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} m-2" id='msg' role='alert'>
      {{ message }}
    </div>

    {% endfor%}
{% endif %}

stylist_app/templates/stylist_app/search_stylist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">

  <div class="row">
    <h4 class = "text-center m-3">Search By Area</h4>
    {% for city in cities %}
      <div class="col-sm-4">
        <h5>{{city}}</h5>
          {% for region in regions %}
            {% if region.city == city%}
              <p><a href="{% url 'stylist_app:searched_stylists' region_pk=region.pk hairstyle_pk=None %}">{{region}} ({{region.stylist_set.all.count}})</a></p>
            {% endif%}
          {% endfor %}

      </div>
    {% endfor %}

<hr>

  <div class="row">
    <h4 class = "text-center mt-3 mb-3">Search By Hairstyle</h4>
    {% for category in categories %}
      <div class="col-sm-4">
        <h5>{{category}}</h5>
          {% for hairstyle in hairstyles %}
            {% if hairstyle.category == category %}
            <p><a href="{% url 'stylist_app:searched_stylists' region_pk=None hairstyle_pk=hairstyle.pk %}">{{hairstyle}} ({{hairstyle.stylist_set.all.count}})</a></p>
            {% endif%}
          {% endfor %}

      </div>
    {% endfor %}

  </div>

</div>
</div>
{% endblock %}

stylist_app/templates/stylist_app/stylist_contact_form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load widget_tweaks %}

  <div class="container">
    <a href="{% url 'stylist_app:stylist_detail' pk=user.stylist.pk %}" class='btn btn-outline-dark m-2'>Back to profile</a>

    <div class="row text-center m-3">
          <h3>Update Location and Contact Details, {{ user.name }}</h3>
    </div>

    <form method="POST" enctype='multipart/form-data' id='stylist_form' data-regions-url="{% url 'ajax_load_regions'%}">
      {% csrf_token %}
      {{ contact_form.as_p }}

      {% for field in form.visible_fields %}
        <div class="form-group">
       <label for="{{ field.id_for_label }}">{{ field.label }}</label>
       {{ field|add_class:'form-control' }}
         {% for error in field.errors %}
           <span class="help-block">{{ error }}</span>
         {% endfor %}
        </div>
      {% endfor %}

      <div class="text-center m-3">
          <button class='btn btn-outline-dark btn-block' name="button">Submit</button>
      </div>
    </form>

    <p style="font-size:80%;">Need help with your profile? <a href="{% url 'contact'%}">Email</a> or Whatsapp us on 079 020 2582</p>

    <div class="alert alert-dark alert-dismissible fade show text-center" role="alert">
        <a href="{% url 'stylist_app:salon_create' pk=user.stylist.pk %}"">Salon not on list? Click here to add Salon Details</a>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script>
    $("#id_city").change(function () {
           var url = $("#stylist_form").attr("data-regions-url");  // get the url of the `load_region` view
           var cityId = $(this).val();  // get the selected country ID from the HTML input

           $.ajax({                       // initialize an AJAX request
               url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
               data: {
                   'city': cityId       // add the country id to the GET parameters
               },
               success: function (data) {   // `data` is the return of the `load_cities` view function
                   $("#id_region").html(data);  // replace the contents of the city input with the data that came from the server
                   /*

                   let html_data = '<option value="">---------</option>';
                   data.forEach(function (city) {
                       html_data += `<option value="${city.id}">${city.name}</option>`
                   });
                   console.log(html_data);
                   $("#id_city").html(html_data);

                   */
               }
           });

       });


  </script>

{% endblock %}

stylist_app/templates/stylist_app/stylist_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load widget_tweaks %}

  <div class="container">
    <a href="{% url 'stylist_app:stylist_detail' pk=user.stylist.pk %}" class='btn btn-outline-dark m-2'>Back to profile</a>

    <div class="row text-center m-3">
          <h3>Update your Profile, {{ user.name }}</h3>
    </div>

    <form method="POST" enctype='multipart/form-data' id='stylist_form' data-regions-url="{% url 'ajax_load_regions'%}">
      {% csrf_token %}
      <!-- user main details -->
      {{ user_form.as_p}}

        <!-- stylist details  -->
      {{ form.media}}
      {{ form.as_p}}

      <!-- stylist contact form details  -->


      <div class="text-center">
        <h3 class='m-3'>Your Contact and Location Details</h3>
      </div>

      <!-- {{ contact_form.as_p}} -->

      {% for field in contact_form.visible_fields %}
        <div class="form-group">
       <label for="{{ field.id_for_label }}">{{ field.label }}</label>
       {{ field|add_class:'form-control' }}
         {% for error in field.errors %}
           <span class="help-block">{{ error }}</span>
         {% endfor %}
        </div>
      {% endfor %}

      <div class="text-center m-3">
          <button class='btn btn-outline-dark btn-block' name="button">Submit</button>
      </div>
    </form>
    <p style="font-size:80%;">Need help with your profile? <a href="{% url 'contact'%}">Email</a> or Whatsapp us on 079 020 2582</p>


    <div class = text-center>
      <div class="btn-group m-4">
        <a href="{% url 'stylist_app:stylist_contact_update' pk=user.stylist.pk%}" class='btn btn-outline-dark ml-1'>Edit Contacts</a>
        <a href="{% url 'stylist_app:service_create' pk=user.stylist.pk%}" class='btn btn-outline-dark ml-1'>Edit Hairstyles</a>
        <a href="{% url 'stylist_app:portfolio_item_create' pk=user.stylist.pk%}" class='btn btn-outline-dark ml-1'>Edit Gallery</a>

      </div>

      <div>
        <a href="{% url 'accounts:user_delete' pk=user.pk %}" class='btn btn-outline-danger ml-1'>Delete Profile</a>
      </div>
    </div>

  </div>


  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script>
    $("#id_city").change(function () {
           var url = $("#stylist_form").attr("data-regions-url");  // get the url of the `load_region` view
           var cityId = $(this).val();  // get the selected country ID from the HTML input

           $.ajax({                       // initialize an AJAX request
               url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
               data: {
                   'city': cityId       // add the country id to the GET parameters
               },
               success: function (data) {   // `data` is the return of the `load_cities` view function
                   $("#id_region").html(data);  // replace the contents of the city input with the data that came from the server
                   /*

                   let html_data = '<option value="">---------</option>';
                   data.forEach(function (city) {
                       html_data += `<option value="${city.id}">${city.name}</option>`
                   });
                   console.log(html_data);
                   $("#id_city").html(html_data);

                   */
               }
           });

       });


  </script>
{% endblock %}