accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('stylist_signup/', views.StylistSignUp.as_view(), name = 'stylist_signup'),
    path('stylist_signup_success', views.stylist_signup_success, name = 'stylist_success'),
    path('client_signup/', views.ClientSignUp.as_view(), name = 'client_signup'),
    path('user_delete//<int:pk>/', views.UserDeleteView.as_view(), name = 'user_delete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),


]

# 1. Submit email form                         -> PasswordResetView.as_view()
# 2. Email sent success message               -> PasswordResetDoneView.as_view(password_reset_done)
# 3. Link to password reset form in mail      -> PasswordResetConfirmView.as_view()
# 4. Password successfully changed message      -> PasswordResetCompleteView.as_view()

client_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'client_app'

urlpatterns = [
    path('client_subscribe/', views.subscription, name='subscribe'),
    path('client_detail/<int:pk>/', views.viewClient, name='client_detail'),
    path('add_favourite/<int:pk>/', views.addFavourite, name='add_favourite'),
    path('remove_favourite/<int:pk>/', views.removeFavourite, name='remove_favourite'),
    path('add_review/<int:pk>/', views.addReview, name='add_review'),
    path('view_review/<int:pk>/', views.viewReview, name='view_review'),
    path('update_review/<int:pk>/', views.updateReview, name='update_review'),
    path('delete_review/<int:pk>/', views.deleteReview, name='delete_review'),
    
]

stylist_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'stylist_app'

urlpatterns = [
    path('stylist_home/', views.StylistHome.as_view(), name = 'stylist_home'),
    path('stylist_detail/<int:pk>/', views.viewStylist, name = 'stylist_detail'),
    path('stylists', views.listStylists, name = 'stylists_view'),
    path('stylist_update/<int:pk>/', views.updateStylist, name = 'stylist_update'),
    path('stylist_contact/<int:pk>/', views.updateStylistContact, name = 'stylist_contact_update'),
    path('service_create/<int:pk>/', views.createService, name = 'service_create'),
    path('service_update/<int:pk>/', views.updateService, name = 'service_update'),
    path('service_delete/<int:pk>/', views.deleteService, name = 'service_delete'),
    path('salon_create/<int:pk>/', views.createSalon, name = 'salon_create'),
    path('portfolio_item_create/<int:pk>/', views.createPortfolio, name = 'portfolio_item_create'),
    path('portfolio_view/<int:pk>/', views.viewPortfolio, name = 'portfolio_view'),
    path('portfolio_update/<int:pk>/', views.updatePortfolio, name = 'portfolio_update'),
    path('portfolio_delete/<int:pk>/', views.deletePortfolio, name = 'portfolio_delete'),
    path('search_stylist/', views.searchStylist, name='search'),
    path('searched_stylist/<region_pk>/<hairstyle_pk>/', views.searchedStylists, name='searched_stylists')

]

accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from datetime import datetime
from django.core.validators import RegexValidator, MaxLengthValidator
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, Transpose



from stylist_app.models import Hairstyle, Product, HairstyleCategory


class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_stylist = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)


    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

    def get_email(self):
        return self.email

class City(models.Model):
    name = models.CharField(max_length = 100, blank=True)

    def __str__(self):
        return self.name

class Region(models.Model):
    name = models.CharField(max_length = 100, blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

class Salon(models.Model):

    name = models.CharField(max_length=128)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.TextField(max_length=128, blank=True)
    phone_number = models.CharField(max_length = 20, null=True, blank=True)

    def __str__(self):
        return self.name

class Stylist(models.Model):

    phone_regex = RegexValidator(regex=r'\d{9,15}', message="Phone number has a minimum of 9 characters and a maximum of 15")

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    profile_pic = ProcessedImageField(upload_to = 'profile_pics/',
                                        processors=[ResizeToFill(280,280), Transpose()],
                                        format='PNG',
                                        options={'quality':100},
                                        default='profile_pics/default_stylist.png')
    phone_number = models.CharField(max_length=17, validators=[phone_regex], blank=True)
    bio = models.TextField(max_length=256, blank=True, null=True)
    house_calls =models.BooleanField(default=False)
    facebook = models.URLField(blank = True)
    instagram = models.URLField(blank = True)
    rating = models.FloatField(default = 0.0, null=True, blank=True)
    hairstyles = models.ManyToManyField(Hairstyle, through='ServiceOffering')
    product = models.ManyToManyField(Product, through='ProductOffering')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, blank=True, null=True)
    salon = models.ForeignKey(Salon, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self):
        return self.user.name

    def get_absolute_url(self):
        return reverse('stylist_app:stylist_detail', kwargs={'pk': self.pk})
            #always return to the detail page of the primary key that was worked on



class ServiceOffering(models.Model):
    hairstyle = models.ForeignKey(Hairstyle,
                                    related_name='style_offers',
                                    on_delete=models.CASCADE)
    category = models.ForeignKey(HairstyleCategory,
                                    related_name='style_categories',
                                    on_delete=models.CASCADE, blank=True, null=True)
    stylist = models.ForeignKey(Stylist,
                                    related_name='stylist_hairstyles',
                                    on_delete=models.CASCADE)
    name = models.CharField(max_length=128, blank=True)
    description = models.TextField(max_length=120, blank=True)
    price = models.FloatField(blank=True, null=True)
    top_style = models.BooleanField(default=False)


    class Meta:
        unique_together = ('hairstyle', 'stylist')



class ProductOffering(models.Model):
    product = models.ForeignKey(Product,
                                    related_name='product_offer',
                                    on_delete=models.CASCADE)

    stylist = models.ForeignKey(Stylist,
                                    related_name='stylist_product',
                                    on_delete=models.CASCADE)

    name = models.CharField(max_length=128)
    description = models.TextField(max_length=254, blank=True)
    price = models.FloatField(blank=True, null=True)

    class Meta:
        unique_together = ('product', 'stylist')

class Portfolio(models.Model):
    stylist = models.ForeignKey(Stylist, on_delete=models.CASCADE)
    hairstyle = models.ForeignKey(Hairstyle, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField(max_length= 128, null=True, blank=True)
    likes = models.IntegerField(default = 0)
    image = models.ImageField(upload_to='portfolio_pics/')
    image_thumbnail = ImageSpecField(source='image',processors=[ResizeToFill(280, 280)], format='JPEG', options={'quality': 200} )


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    fav_hairstlye = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.user.name

class Review(models.Model):
    SCORES = ((1,1), (2,2), (3,3), (4,4), (5,5))

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    stylist = models.ForeignKey(Stylist, on_delete=models.CASCADE)
    value = models.IntegerField(default = 0, choices = SCORES)
    hygiene = models.IntegerField(default = 0, choices = SCORES)
    expectation = models.IntegerField(default = 0, choices = SCORES)
    craft = models.IntegerField(default = 0, choices = SCORES)
    professional = models.IntegerField(default = 0, choices = SCORES)
    comment = models.TextField(max_length= 256, null=True, blank=True)
    recommendation = models.BooleanField(blank=True, null=True)
    total_rating = models.FloatField(blank=True, null=True)
    appointment = models.DateTimeField(default=datetime.now, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)



# Create your models here.

accounts/forms.py
from django import forms
from accounts.models import Stylist, Client, User
from django.db import transaction
from django.contrib.auth.forms import UserCreationForm

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name']

        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),

        }

class StylistSignupForm(UserCreationForm):

    #password = forms.CharField(widget = forms.PasswordInput())  #editing existing attributes

    class Meta():
        model = User
        fields = ('email', 'name')

        # widgets = {
        #     'email': forms.TextInput(attrs={'class':'group'}),
        #     'name': forms.TextInput(attrs={'class':'group'}),
        #     'password': forms.PasswordInput(attrs={'class':'group'}),
        # }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Email'
        self.fields['name'].label = 'Name'



    @transaction.atomic
    def save(self):
        user = super().save(commit = False)
    #add additional attributes for the user e.g user.name = self.cleaned_data.get('name')
        user.is_stylist = True
        user.email = user.email.lower()
        user.save()
        stylist = Stylist.objects.create(user=user)
    #add other attributes for the sylist that you want
        stylist.save()
        return user




class ClientSignupForm(UserCreationForm):

    #password = forms.CharField(widget = forms.PasswordInput())  #editing existing attributes

    class Meta():
        model = User
        fields = ('email', 'name')

    @transaction.atomic
    def save(self):
        user = super().save(commit = False)
        #add additional attributes for the user e.g user.name = self.cleaned_data.get('name')
        user.is_client = True
        user.save()
        client = Client.objects.create(user=user)
        #add other attributes for the sylist that you want
        client.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.core.mail import send_mail

from accounts.models import User, Stylist, Client, City, Region
from accounts.forms import StylistSignupForm, ClientSignupForm
from django.contrib.auth.decorators import login_required
from django.views.generic import (CreateView, DeleteView)

import os
from django.conf import settings



def index(request):
    return render(request, 'index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def user_login(request):
    if request.method == 'POST':

        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        user = authenticate(email=email, password=password)

        if user:
            if user.is_active and user.is_stylist:
                login(request, user)
                messages.success(request, 'Log In Successful')
                return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk':user.stylist.pk}))
            elif user.is_active and user.is_client:
                login(request, user)
                messages.success(request, 'Log In Successful')
                return HttpResponseRedirect(reverse('client_app:client_detail', kwargs={'pk':user.client.pk}))
            elif user.is_active and user.is_staff:
                login(request, user)
                return HttpResponseRedirect(reverse('admin_page'))
            else:
                messages.error(request,'Account in not active')
                return redirect('index')
        else:
            messages.error(request,'Your email or password is incorrect, please try again')
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        return render(request, 'accounts/login.html', {})

class StylistSignUp(CreateView):
    model = User
    form_class = StylistSignupForm
    success_url = reverse_lazy('accounts:stylist_success')
    template_name = 'accounts/stylist_signup.html'


class ClientSignUp(CreateView):
    model = User
    form_class = ClientSignupForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/client_signup.html'

class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('home')


def stylist_signup_success(request):
    subject = "New Hairstylist Has Signed up"
    message = "Congratulations, A new haistylist has signed up."
    email = "DONOTREPLAY@findmyhairstylist.co.za"
    send_mail(subject, message, email, ['mbasa@findmyhairstylist.co.za'], fail_silently=False,)
    return render(request, 'accounts/stylist_success.html', {})

accounts/templates/accounts/client_signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


  <div class="container" style="margin-bottom:20%;">

    <div class="text-center m-3">
      <h2>Sign Up As Client</h2>
    </div>

    <form method="POST" enctype = "multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="Submit" class='btn btn-outline-dark mt-3' name="ClientSignup">
    </form>

    <div class="row text-center">
      <a href="{% url 'accounts:login' %}">Already a member? Log In Here</a>

    </div>

  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container" style="margin-bottom:20%;">

  {% for message in messages %}
    <div class="alert alert-danger m-3">
      <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
   {% endfor %}

    <h1 class='text-center'>Log In</h1>

    <form action="{% url 'accounts:login' %}" method="post">
      {% csrf_token %}

      <div class="row mb-3">
        <label for="email" class="form-label col-sm-2">Email:</label>
        <div class="col-sm-10">
          <input type="email" class="form-control" name="email">
        </div>
      </div>


      <div class="row mb-3">
        <label for="password" class="form-label col-sm-2">Password:</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" name="password">
        </div>

      </div>
      <button type="submit" class="btn btn-outline-dark">Submit</button>
    </form>

    <div class="row text-center">
      <div class="col-sm-3 m-2">

      </div>
      <div class="col-sm-2 m-2">
        <a href="{% url 'accounts:password_reset' %}">Reset Password</a>
      </div>

      <div class="col-sm-2 m-2">
        <a href="{% url 'accounts:stylist_signup' %}">Stylists Sign Up Here</a>
      </div>

      <div class="col-sm-2 m-2">
        <a href="{% url 'client_app:subscribe' %}">Clients Sign Up Here</a>
      </div>
    </div>

</div>



{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
  <h3>Password Reset</h3>

  <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit" name="Reset Password" class="btn btn-outline-dark">
  </form>

</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h3>Password Reset Complete</h3>

  <p>Your password has been set. You may go ahead and log in now. </p>

  <a href="{% url 'accounts:login'%}" class="btn btn-outline-dark">Log In</a>
</div>


{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h3>Password Reset Sent</h3>

  <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. </p>
  <p>If you don't receive and email, please make sure you've entered the email you registered with, and check your <strong>spam folder</strong></p>
  
</div>



{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
  <h3>Enter new password</h3>

  <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

  <form method="post">
  {% csrf_token %}

  {{form.as_p}}

  <input type="Submit" name="Update Password">

  </form>
</div>


{% endblock %}

accounts/templates/accounts/stylist_form.html
{% extends "base.html" %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary" type="Submit" name="" value="Update Profile">

  </form>

{% endblock %}

accounts/templates/accounts/stylist_signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:20%;">

  <div class="text-center m-3">
    <h2>Sign Up As Stylist</h2>
  </div>

  <form method="POST" enctype = "multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="Submit" class='btn btn-outline-dark mt-3' name="StylistSignup">
  </form>

  <div class="row text-center">
    <a href="{% url 'accounts:login' %}">Already a member? Log In Here</a>

  </div>

</div>

{% endblock %}

accounts/templates/accounts/stylist_success.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
  <h3 class="display-5">Welcome</h3>
  <p class="lead">You can now log in and update your profile</p>

  <ul>
    <li>Upload a profile picture</li>
    <li>Create your hairstyle menu</li>
    <li>Add pictures to your gallery</li>
    <li>Add your location and contact details</li>
  </ul>

  <p style="font-size:60%">*The more details your add, the easier it is for your clients</p>

  <a href="{% url 'accounts:login' %}" class="btn btn-outline-dark">Log In</a>

</div>

{% endblock%}

accounts/templates/accounts/user_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
      {% if user.is_stylist %}
        <a href="{% url 'stylist_app:stylist_detail' pk=user.stylist.pk %}" class='btn btn-outline-dark m-2'>Back to profile</a>
      {% endif %}

    <div class="row text-center">

      <h3> Are you sure you want to delete your profile, {{ user.name }}?</h3>
      <h3> All your information will be lost.</h3>

    <form method="POST">
      {% csrf_token %}
      <button type="submit" name="button" class='btn btn-outline-danger'>Confirm Delete</button>
    </form>
    </div>

  </div>
{% endblock %}