accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('stylist_signup/', views.StylistSignUp.as_view(), name = 'stylist_signup'),
    path('stylist_signup_success', views.stylist_signup_success, name = 'stylist_success'),
    path('client_signup/', views.ClientSignUp.as_view(), name = 'client_signup'),
    path('user_delete//<int:pk>/', views.UserDeleteView.as_view(), name = 'user_delete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),


]

# 1. Submit email form                         -> PasswordResetView.as_view()
# 2. Email sent success message               -> PasswordResetDoneView.as_view(password_reset_done)
# 3. Link to password reset form in mail      -> PasswordResetConfirmView.as_view()
# 4. Password successfully changed message      -> PasswordResetCompleteView.as_view()

client_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'client_app'

urlpatterns = [
    path('client_subscribe/', views.subscription, name='subscribe'),
    path('client_detail/<int:pk>/', views.viewClient, name='client_detail'),
    path('add_favourite/<int:pk>/', views.addFavourite, name='add_favourite'),
    path('remove_favourite/<int:pk>/', views.removeFavourite, name='remove_favourite'),
    path('add_review/<int:pk>/', views.addReview, name='add_review'),
    path('view_review/<int:pk>/', views.viewReview, name='view_review'),
    path('update_review/<int:pk>/', views.updateReview, name='update_review'),
    path('delete_review/<int:pk>/', views.deleteReview, name='delete_review'),
    
]

stylist_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'stylist_app'

urlpatterns = [
    path('stylist_home/', views.StylistHome.as_view(), name = 'stylist_home'),
    path('stylist_detail/<int:pk>/', views.viewStylist, name = 'stylist_detail'),
    path('stylists', views.listStylists, name = 'stylists_view'),
    path('stylist_update/<int:pk>/', views.updateStylist, name = 'stylist_update'),
    path('stylist_contact/<int:pk>/', views.updateStylistContact, name = 'stylist_contact_update'),
    path('service_create/<int:pk>/', views.createService, name = 'service_create'),
    path('service_update/<int:pk>/', views.updateService, name = 'service_update'),
    path('service_delete/<int:pk>/', views.deleteService, name = 'service_delete'),
    path('salon_create/<int:pk>/', views.createSalon, name = 'salon_create'),
    path('portfolio_item_create/<int:pk>/', views.createPortfolio, name = 'portfolio_item_create'),
    path('portfolio_view/<int:pk>/', views.viewPortfolio, name = 'portfolio_view'),
    path('portfolio_update/<int:pk>/', views.updatePortfolio, name = 'portfolio_update'),
    path('portfolio_delete/<int:pk>/', views.deletePortfolio, name = 'portfolio_delete'),
    path('search_stylist/', views.searchStylist, name='search'),
    path('searched_stylist/<region_pk>/<hairstyle_pk>/', views.searchedStylists, name='searched_stylists')

]

templates/admin_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Cities and Regions</h2>


  {% for city in cities %}

<h5>{{city.name}} ({{city.regions.count}})</h5>
<a href="{url 'update_city' pk=city.py}" class="btn btn-danger">Update {{city.name}} Regions</a>
  {% for region in regions%}
    <ul>
      {% if region.city == city %}
        <li style="display:inline;">{{region.name}}</li>
      {% endif %}
    </ul>
  {% endfor%}
{% endfor%}







{% endblock%}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="">
<!-- To declare your language - read more here: https://www.w3.org/International/questions/qa-html-language-declarations -->
<head>
<title>FindMyHairstylist</title>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-RBYVB0QFQG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RBYVB0QFQG');
</script>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="ie=edge">


<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
<link href="http://fonts.cdnfonts.com/css/nobel?styles=38375" rel="stylesheet">
<script src="https://kit.fontawesome.com/c1d230121d.js" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>


<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light bg-inverse p-3">
    <a class="navbar-brand" href="{% url 'home'%}"><img src="{% static 'images/FindMyHairstylist_logo.png'%}" style="max-width: 300px"></img></a>

      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto text-center">
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'home'%}">Home</a></li>

{% if user.is_authenticated and user.is_admin %}
          <!-- <li><a class="nav-link" href="{% url 'stylist_app:search'%}">Search</a></li> -->
          <li><a class="nav-link" href="#">Admin Profile</a></li>
          <li><a class="nav-link" href="{% url 'stylist_app:stylists_view' %}">Stylists</a></li>
          <li><a class="nav-link" href="#">Clients</a></li>
          <li><a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a></li>

{% elif user.is_authenticated and user.is_stylist %}
          <li><a class="nav-link" href="{% url 'stylist_app:stylist_detail' pk=user.stylist.pk%}">My Profile</a></li>
          <li><a class="nav-link" href="{% url 'stylist_app:stylists_view' %}">Stylists</a></li>
          <li><a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a></li>

{% elif user.is_authenticated and user.is_client %}
          <li><a class="nav-link" href="{% url 'client_app:client_detail' pk=user.client.pk%}">My Profile</a></li>
          <li><a class="nav-link" href="{% url 'stylist_app:stylists_view' %}">Stylists</a></li>
          <li><a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a></li>

{% else %}
          <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
          <li><a class="nav-link" href="{% url 'accounts:stylist_signup' %}">Stylist-Sign Up </a></li>
          <li><a class="nav-link" href="{% url 'accounts:client_signup' %}">Client-Sign Up</a></li>
          <!-- <li><a class="nav-link" href="{% url 'accounts:client_signup' %}">Client-Sign Up</a></li> -->
{% endif %}
          <li class="nav-item"><a class="nav-link" href="{% url 'contact'%}">Contact Us</a></li>
      </ul>
      </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      </div>
  </nav>






  {% block content %}



  {% endblock %}
</body>

<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">FindMyHairstylist is an
              initiative  by Hairlinkd. Our goal is to assist hairstylists to
              continuously improve their businesses and grow their customer bases.
              Not only do we offer a platform to showcase their skills and talent, we
              provide them with essential tools and information to ensure they succeed.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>SIGN UP NOW</h6>
            <ul class="footer-links">
              <li><a href="{% url 'accounts:stylist_signup' %}">As a Stylist</a></li>
              <li><a href="{% url 'accounts:client_signup'%}">As a Client</a></li>


            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="{% url 'contact' %}">Contact Us</a></li>
              <li><a href="">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by
         <a href="#">Hairlinkd</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>
<!-- JAVASCRIPTS -->

<!-- <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src= "{% static 'js/master.js' %}" ></script>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<section class="contact-page-section">
      <div class="container">
          <div class="sec-title">
            {% if name %}
                <h2>Thank you for reaching out</h2>
                <p class='lead'>We got your message </p>
            {% else %}
              <h2>Keep in touch</h2>
            {% endif %}
            </div>

            <div class="inner-container">
              <div class="row clearfix">

                  <!--Form Column-->
                    <div class="form-column col-md-8 col-sm-12 col-xs-12">
                      <div class="inner-column">

                            <!--Contact Form-->
                            <div class="contact-form">
                                <form method="post" action="{% url 'contact'%}" id="contact-form">
                                  {% csrf_token %}
                                    <div class="row clearfix">
                                        <div class="form-group col-md-6 col-sm-6 co-xs-12">
                                            <input type="text" name="name" placeholder="Name" required>
                                        </div>

                                        <div class="form-group col-md-6 col-sm-6 co-xs-12">
                                            <input type="email" name="email" placeholder="Email" required>
                                        </div>
                                        <div class="form-group col-md-6 col-sm-6 co-xs-12">
                                            <input type="text" name="subject" placeholder="Subject" required>
                                        </div>
                                        <div class="form-group col-md-6 col-sm-6 co-xs-12">
                                            <input type="text" name="phone" placeholder="Phone">
                                        </div>
                                        <div class="form-group col-md-12 col-sm-12 co-xs-12">
                                            <textarea name="message" placeholder="Massage"></textarea>
                                        </div>
                                        <div class="form-group col-md-6 col-sm-6 co-xs-12">
                                            <input type="hidden" name="address" placeholder="address">
                                        </div>
                                        <div class="form-group col-md-12 col-sm-12 co-xs-12">
                                            <button type="submit" class="theme-btn btn-style-one">Send Now</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!--End Contact Form-->

                        </div>
                    </div>

                    <!--Info Column-->
                    <div class="info-column col-md-4 col-sm-12 col-xs-12">
                      <div class="inner-column">
                          <h6>Contact Info</h6>
                            <ul class="list-info">
                              <li><i class="fas fa-globe"></i>2 Sungai, Hornbill Road, Douglasdale</li>
                              <li><i class="fas fa-phone"></i</li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/hairstyle_dropdown_options.html
<option value="">---------</option>
{% for hairstyle in hairstyles %}
<option value="{{ hairstyle.pk }}">{{ hairstyle.name }}</option>
{% endfor %}

templates/index.html
{% extends 'base.html'%}

{% load static %}

{% block content %}


<div class="alert alert-success alert-dismissible fade show" role="alert">
  All Hairstylists from <strong>Gauteng</strong> are invited to Sign Up for FREE'
  <a type="button" class="close" style="float:right;" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">X</span></a>

</div>



<div class="hero" style="background: url('static/images/div1_bg.png') no-repeat center center scroll;
                            background-size: cover; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: contain;">
  <div class="container div_1_text">
        <h1 class="display-4"">Find that perfect Hairstylist</h1>
          <p class="lead">There are hairstylists out there, that cater for your unique needs.</p>
          <p class="lead">We'll help you find them.</p>
        <a href="{% url 'accounts:client_signup' %}" class="btn btn-dark m-1">Client - Sign Up</a>
        <a href="{% url 'accounts:stylist_signup' %}" class="btn btn-dark m-1">Stylist - Sign Up</a>
  </div>
</div>

<div class="container">
  <blockquote class="blockquote text-center mt-5 mb-5">
      <p class="mb-0">"Life is more beautiful when you meet the right <span style="color:red;">hairstylist</span>."</p>

    <p style="font-size:80%;">&ndash; <em>Peter Coppola</em></p>
  </blockquote>

</div>


<div class="container h-100">
  <div class="row mt-3">
    <div class="col-sm-6 mb-5">
      <h3 class="display-6"">Find that perfect Hairstylist, everytime</h3>

      <div class="mt-3">
        <p class="lead">Sign Up as a Client for free</p>
        <ul class="lead">
          <li>Find that Hairstylist for your exact needs</li>
          <li>Connect with Hairstylists near you</li>
          <li>View menus and galleries</li>
          <li>View ratings and reviews</li>
        </ul>

        <a href="{% url 'accounts:client_signup' %}" class="btn btn-outline-dark">Client - Sign Up</a>
      </div>

    </div>
    <div class="col-sm-6 mb-3">
      <img src="{% static 'images/Client_2.jpg'%}" class="card-img-top" alt="...">
      </div>
    </div>
  </div>

  <div class="container">
    <blockquote class="blockquote text-center mt-5 mb-5">
        <p class="mb-0">"Blessed are the <span style="color:red;">hairstylists</span>, for they bring out the beauty in others."</p>
        <p style="font-size:80%;">&ndash; <em>Anonymous</em></p>
    </blockquote>
  </div>


  <div class="container h-100">
    <div class="row mt-5">

      <div class="col-sm-6 mb-5 ">
        <img src="{% static 'images/Stylist_3.jpg'%}" class="card-img-top" alt="...">
      </div>

      <div class="col-sm-6 mb-5">
        <h3 class="display-6"">Be that perfect Hairstylist, everytime</h3>

        <div class="mt-3">
          <p class="lead">Sign Up as a Hairstylist for free</p>
          <ul class="lead">
            <li>Grow and maintain your client base</li>
            <li>Standout from other Hairstylist</li>
            <li>Work with clients that matter</li>
            <li>Learn about your clients changing needs</li>
          </ul>

          <a href="{% url 'accounts:stylist_signup' %}" class="btn btn-outline-dark">Stylist - Sign Up</a>
        </div>
      </div>



    </div>
  </div>

<div class="container">
    <div class="row text-center mt-4 mb-5">
      <div class="mb-3">
        <h3 class="display-5 mb-2"> Meet the lastest hairstylists</h3>
      </div>


      {% for stylist in stylists %}
      <div class="col-md-4">
        <div class="card m-1" style="width: 16rem;">
          <div class= "text-center m-2">
            <a  href="{% url 'stylist_app:stylist_detail' pk=stylist.pk %}">
            <img src="{{ stylist.profile_pic.url }}" alt=" No Picture here" class="image--cover"></a>
          </div>

          <div class="card-body">
            <h5 class="card-title">{{ stylist.user.name }}
              <span class="badge bg-secondary">{{stylist.rating|floatformat:1}} </span></h5>
              {% if stylist.region %}
                <h6 class="card-text">{{stylist.region}} ({{stylist.region.city}})</h6>
              {% endif %}
                <p><strong>Speciality:</strong>
                  {% for service in services %}
                    {% if service.stylist == stylist and service.top_style == True %}
                      {{service.hairstyle.name}}|
                    {% endif%}
                  {% endfor %}</p>

            <p class="card-text">{{stylist.bio|safe|truncatechars:"50"|linebreaks}}</p>
            <a class="btn btn-outline-dark" href="{% url 'stylist_app:stylist_detail' pk=stylist.pk %}">View Profile</a>
          </div>
        </div>
      </div>
      {% endfor%}

      <h3 class="display-5 mt-3">All Hairstylists or Barbers can Sign Up for Free</h3>
      <hr>
      <p class = "lead">Sign up now and start growing your client base and hair business</p>
      <a href="{% url 'accounts:stylist_signup' %}" class="btn btn-outline-dark">Stylist - Sign Up</a>
</div>

</div>



{% endblock %}

templates/region_dropdown_options.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.pk }}">{{ region.name }}</option>
{% endfor %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
  <h1>You are now logged in hairlinkd</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <h1>You are now logged off</h1>

{% endblock %}