accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('stylist_signup/', views.StylistSignUp.as_view(), name = 'stylist_signup'),
    path('stylist_signup_success', views.stylist_signup_success, name = 'stylist_success'),
    path('client_signup/', views.ClientSignUp.as_view(), name = 'client_signup'),
    path('user_delete//<int:pk>/', views.UserDeleteView.as_view(), name = 'user_delete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),


]

# 1. Submit email form                         -> PasswordResetView.as_view()
# 2. Email sent success message               -> PasswordResetDoneView.as_view(password_reset_done)
# 3. Link to password reset form in mail      -> PasswordResetConfirmView.as_view()
# 4. Password successfully changed message      -> PasswordResetCompleteView.as_view()

client_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'client_app'

urlpatterns = [
    path('client_subscribe/', views.subscription, name='subscribe'),
    path('client_detail/<int:pk>/', views.viewClient, name='client_detail'),
    path('add_favourite/<int:pk>/', views.addFavourite, name='add_favourite'),
    path('remove_favourite/<int:pk>/', views.removeFavourite, name='remove_favourite'),
    path('add_review/<int:pk>/', views.addReview, name='add_review'),
    path('view_review/<int:pk>/', views.viewReview, name='view_review'),
    path('update_review/<int:pk>/', views.updateReview, name='update_review'),
    path('delete_review/<int:pk>/', views.deleteReview, name='delete_review'),
    
]

stylist_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #so that we don't confuse with our own views (allows us to use LoginView and LogoutView)
from . import views

app_name = 'stylist_app'

urlpatterns = [
    path('stylist_home/', views.StylistHome.as_view(), name = 'stylist_home'),
    path('stylist_detail/<int:pk>/', views.viewStylist, name = 'stylist_detail'),
    path('stylists', views.listStylists, name = 'stylists_view'),
    path('stylist_update/<int:pk>/', views.updateStylist, name = 'stylist_update'),
    path('stylist_contact/<int:pk>/', views.updateStylistContact, name = 'stylist_contact_update'),
    path('service_create/<int:pk>/', views.createService, name = 'service_create'),
    path('service_update/<int:pk>/', views.updateService, name = 'service_update'),
    path('service_delete/<int:pk>/', views.deleteService, name = 'service_delete'),
    path('salon_create/<int:pk>/', views.createSalon, name = 'salon_create'),
    path('portfolio_item_create/<int:pk>/', views.createPortfolio, name = 'portfolio_item_create'),
    path('portfolio_view/<int:pk>/', views.viewPortfolio, name = 'portfolio_view'),
    path('portfolio_update/<int:pk>/', views.updatePortfolio, name = 'portfolio_update'),
    path('portfolio_delete/<int:pk>/', views.deletePortfolio, name = 'portfolio_delete'),
    path('search_stylist/', views.searchStylist, name='search'),
    path('searched_stylist/<region_pk>/<hairstyle_pk>/', views.searchedStylists, name='searched_stylists')

]

client_app/models.py
from django.db import models
from accounts.models import Stylist, Client

class Favourite(models.Model):
    client = models.ForeignKey(Client, related_name='client_favourite'
                                ,on_delete=models.CASCADE)
    stylist = models.ForeignKey(Stylist, related_name='stylist_as_favourite'
                                ,on_delete=models.CASCADE)

    class Meta:
        unique_together = ('client', 'stylist')





# Create your models here.

client_app/forms.py
from django import forms
from django.forms.widgets import NumberInput
from accounts.models import Review
from django.core.exceptions import ValidationError


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['appointment', 'value', 'hygiene', 'expectation',
                    'craft', 'professional', 'comment', 'recommendation']
        field_order = ['appointment', 'value', 'hygiene', 'expectation',
                    'craft', 'professional', 'comment', 'recommendation']

        labels = {
            'appointment': 'Date of Appointment',
            'value': 'Value for My Money',
            'hygiene': 'Hygiene (e.g. Covid precautions, cleanliness)',
            'expectation': 'Expectations Met (I got what I was looking for)',
            'craft': 'Craft ( e.g. Skill, Creativity, Care, Condifence)',
            'professional':'Professionalism (e.g. Time management, Communication, Focus)',
            'recommendation': 'Would you recommend this hairstylist?'
        }

        SCORES =[
            ('1', '1'),('2', '2'),
            ('3', '3'),('4', '4'),
            ('5', '5'),
        ]


        widgets = {
            'appointment' : forms.DateInput(attrs={'type':'date', 'class':'form-control mb-4'}),
            'value' : forms.Select(attrs={'class': 'form-control mb-4'}),
            'hygiene' : forms.Select(attrs={'class': 'form-control mb-4'}),
            'expectation' : forms.Select(attrs={'class': 'form-control mb-4'}),
            'craft' : forms.Select(attrs={'class': 'form-control mb-4'}),
            'professional' : forms.Select(attrs={'class': 'form-control mb-4'}),
            'comment' : forms.Textarea(attrs={'placeholder': 'Tell us more. e.g. Why did you rate as you did? Any room for improvement?', 'class': 'form-control mb-4'}),
            'recommendation' : forms.NullBooleanSelect(attrs={'class': 'form-control mb-4'}),
        }

        def clean(self):
            all_clean_data = super().clean()
            appointment_date = all_clean_data['appointment']
            review_date = all_clean_data['created']
            if review_date == appointment_date:
                raise forms.ValidationError('Your appointment has to be in the past')

client_app/views.py
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from mailchimp_marketing import Client
from accounts.models import Stylist, Client, Review, ServiceOffering
from client_app.models import Favourite
from .forms import ReviewForm
from mailchimp_marketing.api_client import ApiClientError
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db import IntegrityError
from django.db.models import Avg


# Mailchimp Settings
api_key = settings.MAILCHIMP_API_KEY
server = settings.MAILCHIMP_DATA_CENTER
list_id = settings.MAILCHIMP_EMAIL_LIST_ID


@login_required
def viewClient(request, pk):
    client = Client.objects.get(pk = pk)
    favourite_stylists = Favourite.objects.filter(client=client)
    reviews = Review.objects.filter(client=client)



    context = {'client':client, 'favourite_stylists':favourite_stylists, 'reviews':reviews}
    return render(request, 'client_app/client_details.html', context)


def addFavourite(request, pk):
    user = request.user
    client = user.client
    stylist = Stylist.objects.get(pk=pk)
    favourite = Favourite(client=client, stylist=stylist)
    try:
        favourite.save()
        messages.success(request, 'Added to your favourites')
        return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))
    except IntegrityError:
        messages.error(request, 'Oops, Looks like this hairstylist is already in your favourites')
        return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))


def removeFavourite(request, pk):
    client = request.user.client
    favourite = Favourite.objects.get(pk=pk)

    favourite.delete()
    return HttpResponseRedirect(reverse('client_app:client_detail', kwargs={'pk': client.pk}))


def updateTotalRating(pk):
    stylist = Stylist.objects.get(pk=pk)
    average_score = Review.objects.filter(stylist=stylist).aggregate(Avg('total_rating'))

    stylist.rating = average_score['total_rating__avg']

    if not stylist.rating:
        stylist.rating = 0.0
        
    stylist.save()


def addReview(request, pk):
    client = request.user.client
    stylist = Stylist.objects.get(pk=pk)
    rating = stylist.rating
    form = ReviewForm
    new_rating = 0

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.client = client
            instance.stylist = stylist
            instance.total_rating = (instance.value+instance.hygiene+instance.expectation+instance.craft+instance.professional)/5
            form.save()
            updateTotalRating(stylist.pk)

            messages.success(request, 'Your review has been added')
            return HttpResponseRedirect(reverse('client_app:view_review', kwargs={'pk': instance.pk}))

    context = {'form':form, 'stylist':stylist}
    return render(request, 'client_app/review.html', context)

def viewReview(request, pk):
    review = Review.objects.get(pk=pk)

    context = {'review': review}
    return render(request, 'client_app/view_review.html', context)

def updateReview(request, pk):
    review = Review.objects.get(pk=pk)
    client = review.client
    stylist = review.stylist

    form = ReviewForm(instance=review)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.total_rating = (instance.value+instance.hygiene+instance.expectation+instance.craft+instance.professional)/5
            form.save()
            updateTotalRating(stylist.pk)
            messages.success(request, 'Review updated')
            return HttpResponseRedirect(reverse('client_app:view_review', kwargs={'pk': review.pk}))

    context = {'form': form, 'stylist':stylist}
    return render(request, 'client_app/review.html', context)


def deleteReview(request, pk):
    review = Review.objects.get(pk=pk)
    client = review.client
    stylist = review.stylist

    if request.method == 'POST':
        review.delete()
        updateTotalRating(stylist.pk)
        messages.success(request, 'Your review has been deleted')
        return HttpResponseRedirect(reverse('stylist_app:stylist_detail', kwargs={'pk': stylist.pk}))

    context = {'review': review}
    return render(request, 'client_app/delete_review.html', context)

# Subscription Logic
def subscribe(email):
    """
     Contains code handling the communication to the mailchimp api
     to create a contact/member in an audience/list.
    """

    mailchimp = Client()
    mailchimp.set_config({
        "api_key": api_key,
        "server": server,
    })

    member_info = {
        "email_address": email,
        "status": "subscribed",
    }

    try:
        response = mailchimp.lists.add_list_member(list_id, member_info)
        print("response: {}".format(response))
    except ApiClientError as error:
        print("An exception occurred: {}".format(error.text))


def subscription(request):
    if request.method == "POST":
        email = request.POST['email']
        name = request.POST['name']
        subject = 'New Subscriber'
        message = 'Congratulations, you have a new subscriber'

        if not name:
            subscribe(email)
            send_mail(
                subject,
                message,
                email,
                ['mbasa@findmyhairstylist.co.za'],
                fail_silently=False,
            )
            messages.success(request, "You have been subscribed. Thank You! ")
        else:
            messages.success(request, "Sent")
    return render(request, 'client_app/subscribe.html', {})

client_app/templates/client_app/_client_search.html
{% load static %}
<div class="tab-pane fade show active" id="nav-find" role="tabpanel" aria-labelledby="nav-home-tab">

  <h4 class="display-5 text-center mb-3">Find My Hairstylists</h4>

  <div class="row">
    <div class="col-md-6 mb-4">
      <h4 class="text-center">Basic Search</h4>
      <p class="lead">Use basic search to find your perfect hairstylists in your area</p>
      <p>Available for all users</p>
      <div class="text-center">
        <a href="{% url 'stylist_app:stylists_view'%}" class='btn btn-outline-dark text-center'>Basic Search</a>
      </div>


    </div>
    <div class="col-md-6 mb-4">
      <h4 class="text-center">Advanced Search</h4>
      <p class="lead">Tell us about your unique preferences and we'll recommend a hairstylist for you</p>
      <p>Not available (Coming Soon)</p>

      <div class="text-center">
        <a href="#" class='btn btn-outline-dark'>Advanced Search</a>
      </div>

    </div>
  </div>

</div>

client_app/templates/client_app/_favourite_stylists.html
{% load static %}

<div class="tab-pane fade" id="nav-favourites" role="tabpanel" aria-labelledby="nav-favourites-tab">

  <h4 class="display-5 text-center mb-3 text-center">My Favourite Hairstylists</h4>
  <div class="row">

  {% if favourite_stylists %}

    {% for favourite in favourite_stylists%}
      <div class="card m-1" style="width: 18rem;">
        <div class= "text-center m-2">
          <a  href="{% url 'stylist_app:stylist_detail' pk=favourite.stylist.pk %}">
          <img src="{{ favourite.stylist.profile_pic.url }}" alt=" No Picture here" class="image--cover"></a>
        </div>

        <div class="card-body">
          <h5 class="card-title">{{ favourite.stylist.user.name }}
            <span class="badge bg-secondary">{{favourite.stylist.rating|floatformat:1}} </span></h5>
            {% if favourite.stylist.region %}
              <h6 class="card-text">{{favourite.stylist.region}} ({{favourite.stylist.region.city}})</h6>
            {% endif %}


          <p class="card-text">{{favourite.stylist.bio|safe|truncatechars:"50"|linebreaks}}</p>

          <a class="btn btn-outline-dark m-1" href="{% url 'stylist_app:stylist_detail' pk=favourite.stylist.pk %}">View Profile</a>
          <a class="btn btn-outline-danger m-1" href="{% url 'client_app:remove_favourite' pk=favourite.pk %}"> Remove</a>


        </div>
      </div>
    {% endfor%}



  {% else %}
    <p class='lead'>You don't have any favourite hairstylist yet. Search through the hairstylists and save your favourites.</p>
    <a class="btn btn-outline-dark m-1" href="{% url 'stylist_app:stylists_view' %}">Search Hairstylists</a>
  {% endif %}

  </div>
</div>

client_app/templates/client_app/_preferences.html
{% load static %}

client_app/templates/client_app/_recommended.html
{% load static %}
<div class="tab-pane fade" id="nav-recommended" role="tabpanel" aria-labelledby="nav-recommended-tab">
  <h4 class="display-5 text-center mb-3 text-center">Recommended Hairstylists</h4>

  <div class="row">
    <p class='lead'>Tell us about your unique preferences and we'll personally recommend the best hairstylist for you. Your recommendations will appear here.</p>
    <p class='text-center'><strong>Coming Soon</strong></p>
    <a class="btn btn-outline-dark m-1" href="#">Edit Preferences</a>
  </div>
</div>

client_app/templates/client_app/_reviews.html
{% load static %}

<div class="tab-pane fade" id="nav-reviews" role="tabpanel" aria-labelledby="nav-reviews-tab">
  <h4 class="display-5 text-center mb-3 text-center">My Reviewed Hairstylists</h4>

    <div class="row">
    {% if reviews %}
      {% for review in reviews %}

          <div class="col-sm-3 text-center">
            <ul style="list-style-type:none;"">
              <a  href="{% url 'stylist_app:stylist_detail' pk=review.stylist.pk %}">

              <img src="{{ review.stylist.profile_pic.url }}" style="width:50%; height:auto;" alt=" No Picture here" class="image--cover"></a>

              <li>{{review.stylist.user.name}}</li>
              <li style="font-size:150%"><span class="badge bg-secondary">{{review.total_rating}}</span></li>

            </ul>
          </div>

          <div class="col-sm-9">
            <ul style="list-style-type:none;">
              <li><strong>Appointment:</strong> {{review.appointment|date:"D, d-m-Y"}}</li> <br>
              <li><strong>Money:</strong> {{review.value}}/5, <strong>Hygiene:</strong> {{review.hygiene}}/5, <strong>Expectations:</strong> {{review.expectation}}/5,
                  <strong>Skill:</strong> {{review.craft}}/5, <strong>Professionalism:</strong> {{review.professional}}/5</li><br>
              <li><em>'{{review.comment}}'</em></li><br>
              <li><strong>Recommended:</strong> {{review.recommendation}}</li>

                {% if user.pk == review.client.user.pk %}
                  <a class='btn btn-outline-dark' href="{% url 'client_app:update_review' pk=review.pk%}">Edit</a>
                  <a class='btn btn-outline-danger' href="{% url 'client_app:delete_review' pk=review.pk%}">Delete</a>
                {% endif %}

            </ul>
          </div>
          <hr>



      {% endfor%}
    {% else %}
      <p class='lead'>You currently don't have any reviews. After visiting your hairstylists, you can review them here.</p>
      <a class="btn btn-outline-dark m-1" href="{% url 'stylist_app:stylists_view' %}">Search Hairstylists</a>
    {% endif %}
    </div>
  </div>

client_app/templates/client_app/client_details.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="container">
<p class="mt-4" style='float:right;'>Hello {{client}}</p>
<hr style="clear:both">


<nav>
  <div class="nav nav-tabs mb-5" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-find-tab" data-bs-toggle="tab"
      data-bs-target="#nav-find" type="button" role="tab" aria-controls="nav-find"
       aria-selected="true">Find</button>
    <button class="nav-link" id="nav-favourites-tab" data-bs-toggle="tab" data-bs-target="#nav-favourites" type="button" role="tab" aria-controls="nav-favourites" aria-selected="false">Favourites</button>
    <button class="nav-link" id="nav-reviews-tab" data-bs-toggle="tab" data-bs-target="#nav-reviews" type="button" role="tab" aria-controls="nav-reviews" aria-selected="false">Reviews</button>
    <button class="nav-link" id="nav-recommended-tab" data-bs-toggle="tab" data-bs-target="#nav-recommended" type="button" role="tab" aria-controls="nav-recommended" aria-selected="false">Recommended</button>
  </div>
</nav>


  <div class="tab-content" id="nav-tabContent">
    {% include "client_app/_client_search.html" %}
    {% include "client_app/_favourite_stylists.html" %}
    {% include "client_app/_reviews.html" %}
    {% include "client_app/_recommended.html" %}
  </div>

</div>

{% endblock %}

client_app/templates/client_app/delete_review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
      <a href="{% url 'client_app:delete_review' pk=review.pk %}" class='btn btn-outline-dark m-2'>Back to profile</a>

    <div class="row text-center">
      <h3> Are you sure you want to your review? All information will be lost.</h3>


    <form method="POST">
      {% csrf_token %}
      <button type="submit" name="button" class='btn btn-outline-danger'>Confirm Delete</button>
    </form>
    </div>

  </div>
{% endblock %}

client_app/templates/client_app/review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <a href="{% url 'stylist_app:stylist_detail' pk=stylist.pk%}" class='btn btn-outline-dark m-2'>Back to Hairstylist</a>

    <div class="text-center m-3">
          <h3>How well did {{ stylist.user.name }} do?</h3>
          <p><em><strong>NB:</strong> You can only review hairstylists you have visited</em></p>
    </div>
    <div class="scale">
      <p><strong>Rating Scale: </strong>1 = Horrible, 5 = Excellent</p>

    </div>

    <form method="POST" enctype='multipart/form-data' class='m-3'>
      {% csrf_token %}
      {{form}}

      <button class='btn btn-outline-dark m-3' name="button">Submit</button>
    </form>

    <p style="font-size:80%;">Need help with your review? <a href="{% url 'contact'%}">Email</a> or Whatsapp us on 079 020 2582</p>

  </div>
{% endblock %}

client_app/templates/client_app/subscribe.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">

  <div class="text-center mb-4">
    <h4 class=display-5>Clients Page</h4>
    <p class="lead">Soon you will be able to find that perfect hairstylist for your exact needs, wherever you are!!</p>
    <p class ="lead">Launching: <strong>Friday, October 1, 2021</strong></p>
    <h5></h5>
      <div class="row">
        <div class="col-sm-6">

          <div class="block">
            <span class="digit" id="months"></span>
            Months
          </div>

          <div class="block">
            <span class="digit" id="days"></span>
            Days
          </div>

        </div>

        <div class="col-sm-6">
          <div class="block">
            <span class="digit" id="hours"></span>
            Hours
          </div>

          <div class="block">
            <span class="digit" id="minutes"></span>
            Minutes
          </div>

          <div class="block">
            <span class="digit" id="seconds"></span>
            Seconds
          </div>
        </div>
      </div>


  </div>
<hr>
<div class="row">
  <div class="col-sm-6 mb-5">

    <div class="subscribe_class mt-5">
      <h5>Subscribe now for updates</h5>
      <p style="font-size:80%;"><em>We hate spam more than you do, your details are kept confidential</em></p>
    </div>

    <form method="post" action="{% url 'client_app:subscribe' %}">
      {% csrf_token %}

      <div class="form-group mb-3">
        <input type="email" name="email" class="form-control" placeholder="Enter your Email">
      </div>
      <div>
        <input type="hidden" name="name" class="form-control" placeholder="Name">
      </div>

      <div class="text-center">
          <button class="btn btn-warning" type="submit">Subscribe</button>
      </div>

    </form>
  </div>

  <div class="col-sm-6">
<img src="{% static 'images/happy_client.jpg'%}" class="card-img-top" alt="...">
  </div>

</div>
</div>




{% if messages %}
  {% for message in messages %}
    <div class="my-5 alert alert-success">
      <h5 class="m-0">
          {{ message }}
      </h5>
    </div>
  {% endfor %}
{% endif %}


<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script>
  $(document).ready(function(){
    var dateString = new Date().getFullYear() + "/09/30";
    var deadline = new Date(dateString);

    function updateClock(){
    var today = Date();
    var diff = Date.parse(deadline) - Date.parse(today);
      if(diff<=0){
        clearInterval(interval);
      }
      else{
    var seconds = Math.floor((diff/1000)%60);
    var minutes = Math.floor((diff/1000/60)%60);
    var hours = Math.floor((diff/1000/60/60)%24);
    var days = Math.floor(diff/(1000*60*60*24)%30.5);
    var months = Math.floor(diff/(1000*60*60*24*30.5)%12);

       $("#months").text(('0'+months).slice(-2));
       $("#days").text(('0'+days).slice(-2));
       $("#hours").text(('0'+hours).slice(-2));
       $("#minutes").text(('0'+minutes).slice(-2));
       $("#seconds").text(('0'+seconds).slice(-2));

      }//EOF ELSE

    }//EOF FUNCTION

   var interval = setInterval(updateClock,1000);

  });//EOF DOCUMENT.READY
</script>
{% endblock %}

client_app/templates/client_app/view_review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <a href="{% url 'stylist_app:stylist_detail' pk=review.stylist.pk%}" class='btn btn-outline-dark m-2'>Back to Hairstylist</a>
  <h4 class='text-center'>Summary of {{review.stylist.user.name}}'s Reviews</h4>

  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Reviewed by:</strong> {{review.client.user.name}}</li>
    <li class="list-group-item"><strong>Appointment date:</strong> {{review.appointment|date:"D, d-m-Y"}}</li>
    <li class="list-group-item"><strong>Value for money:</strong> {{review.value}}/5</li>
    <li class="list-group-item"><strong>Hygiene:</strong> {{review.hygiene}}/5</li>
    <li class="list-group-item"><strong>Expectations met:</strong> {{review.expectation}}/5</li>
    <li class="list-group-item"><strong>Craft/Skill:</strong> {{review.craft}}/5</li>
    <li class="list-group-item"><strong>Professionalism:</strong> {{review.professional}}/5</li>
    <li class="list-group-item"><strong>Comments:</strong> {{review.comment}}</li>
    <li class="list-group-item"><strong>Would you recommend {{review.stylist.user.name}}?:</strong> {{review.recommendation}}</li>
    <li class="list-group-item"><strong>Total Average Rating</strong> {{review.total_rating}}/5</li>
  </ul>


      {% if user.pk == review.client.user.pk %}
        <a href="{% url 'stylist_app:stylist_detail' pk=review.stylist.pk%}" class='btn btn-outline-dark m-2'>Submit</a>
        <a class='btn btn-outline-dark' href="{% url 'client_app:update_review' pk=review.pk%}">Edit</a>
        <a class='btn btn-outline-danger' href="{% url 'client_app:delete_review' pk=review.pk%}">Delete</a>
      {% endif %}

</div>

{% endblock %}